name: Test and Rubocop

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: rubocop
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3

    - name: Install project dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RuboCop
      run: rubocop -A

  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3

    - name: Setup Chrome
      uses: actions/setup-chrome@v1

    - name: Set Chrome binary
      run: export CHROME_BIN=${{ env.CHROME_BIN }}

    - name: Install project dependencies
      run: |
        gem install bundler
        bundle install

    - name: Setup DB, Run tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGDATABASE: postgres
        PGPASSWORD: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        bin/rails db:create db:migrate
        bundle exec rspec


    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage
