name: Test and Rubocop

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3

    - name: Install project dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RuboCop
      run: rubocop -A

  test:
    name: Test
    runs-on: ubuntu-latest
    env: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
    
    - name: Install project dependencies
      run: |
        gem install bundler
        bundle install

    - name: Wait for database
      run: |
        until nc -z localhost 5432; do echo "Waiting for Postgres..."; sleep 1; done

    - name: Database setup
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
        bundle exec rails db:migrate

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage
